export const administrator = [
    'dashboard',
    'plantation',
    'harvest',
    'target',
    'statistic',
    'varieties',
    'users',
    'roles',
    'rules',
    'conclusions',
    'verification-agronomy',
    'group',
    'prediction',
    'fertilizer',
    'advertisement',
    'faq',
    'account',
]
export const member = [
    'dashboard',
    'plantation',
    'harvest',
    'target',
    'statistic',
    'verification-agronomy',
    'group',
    'rainfall',
    'prediction',
    'fertilizer',
    'faq',
    'account',
]
export const author = ['articles', 'news', 'advertisement', 'faq', 'account']
